### ISSUE TITLE
Update the testing config.yml to be system-generic (or at least run on travis)

### ISSUE THREAD

**Issue by DanielMarchand** [aiidateam/aiida-wannier90#29]
The current testing config file has many hard-coded parameters, e.g.: 

```
codes:
  wannier90:
    description: Wannier90
    default_plugin: wannier90.wannier90
    remote_computer: localhost
    remote_abspath: /home/greschd/software/wannier90-latest/wannier90.x

```

This should be updated to be generic.
